import { MoveDirection } from './interface.js';
export const MIN_UNIT = 10;
export const MIN_WIDTH = 2;
export const MIN_HEIGHT = 2;
export const MAX_WIDTH = 50;
export const MAX_HEIGHT = 50;
export const DEFAULT_WINSIZE = { width: 20, height: 20 };
export const DEFAULT_SCORE = 1;
export const MAX_LEVEL = 10;
export const BASE_SCORE = 3;
export const DEFAULT_FOODSCORE = 1;
export const DEFAULT_FOOD_POINT = { x: 15, y: 15 };
export const DEFAULT_SNAKE_POINT = { x: 0, y: 0 };
export const DEFAULT_SNAKE_MOVEDIRECTION = MoveDirection.RIGHT;
export const DEFAULT_TIMEOUT = 300;
export const DEFAULT_ISALIVE = true;
export const DEFAULT_NOCLIP = false;
export const DEFAULT_DECLINE = 20;
